import { Platform, StyleSheet } from 'react-native';

import { Palette, Spacing } from '@/constants/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  keyboardView: {
    flex: 1,
  },
  inner: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.four,
    gap: Spacing.five,
  },
  header: {
    alignItems: 'center',
    gap: Spacing.two,
  },
  title: {
    fontFamily: 'Sora_700Bold',
    fontSize: 48,
    color: Palette.mauve,
    textAlign: 'center',
    letterSpacing: 1,
    textShadowColor: Palette.majorelleBlue,
    textShadowRadius: 24,
  },
  greet: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.two,
    alignSelf: 'stretch',
  },
  bubbleWrap: {
    position: 'relative',
    flexShrink: 1,
  },
  bubble: {
    backgroundColor: '#ffffff',
    borderRadius: 18,
    borderWidth: 3,
    borderColor: '#1d1456',
    paddingHorizontal: 16,
    paddingVertical: 10,
    maxWidth: 200,
  },
  bubbleText: {
    color: '#1d1456',
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  tailOuter: {
    position: 'absolute',
    left: -13,
    top: '50%',
    marginTop: -12,
    width: 0,
    height: 0,
    borderTopWidth: 12,
    borderBottomWidth: 12,
    borderRightWidth: 14,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderRightColor: '#1d1456',
  },
  tailInner: {
    position: 'absolute',
    left: -8,
    top: '50%',
    marginTop: -8,
    width: 0,
    height: 0,
    borderTopWidth: 8,
    borderBottomWidth: 8,
    borderRightWidth: 10,
    borderTopColor: 'transparent',
    borderBottomColor: 'transparent',
    borderRightColor: '#ffffff',
  },
  card: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: 'rgba(30, 24, 58, 0.7)',
    borderRadius: 28,
    borderWidth: 1,
    borderColor: 'rgba(171, 129, 205, 0.35)',
    padding: Spacing.four,
    gap: Spacing.three,
    shadowColor: Palette.majorelleBlue,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10,
  },
  inputWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: Palette.dustyGrape,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.04)',
    paddingHorizontal: 14,
  },
  inputWrapFocused: {
    borderColor: Palette.majorelleBlue,
  },
  inputIcon: {
    marginRight: 10,
  },
  input: {
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    color: '#f3eefb',
    paddingVertical: 12,
    ...Platform.select({
      web: { outlineWidth: 0, outlineStyle: 'none' } as object,
      default: {},
    }),
  },
  btn: {
    backgroundColor: Palette.majorelleBlue,
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: 'center',
    shadowColor: Palette.majorelleBlue,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 8,
    elevation: 6,
  },
  btnDisabled: {
    backgroundColor: 'rgba(87, 74, 226, 0.35)',
    shadowOpacity: 0,
    elevation: 0,
  },
  btnPressed: {
    backgroundColor: '#463cc4',
    transform: [{ scale: 0.98 }],
  },
  btnText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
    letterSpacing: 0.4,
  },
});
